#!/bin/sh -e

cd `dirname $0`
install="install -bC"


echo "Check and run printed commands manually." >&2


git ls-files | while read f
do
	[ $f = gather     ] && continue
	[ $f = install    ] && continue
	[ $f = .gitignore ] && continue

	if ! cmp -s $f ~/$f
	then
		dir=`dirname $f`
		[ -d ~/$dir ] || echo mkdir -p ~/$dir
		echo $install $f ~/$f
	fi
done


[ -e ~/.vimrc ] || echo ln -s  ~/.config/nvim/init.vim ~/.vimrc

[ -d ~/.nvim-tmp/backup ] || echo mkdir -p ~/.nvim-tmp/backup
[ -d ~/.nvim-tmp/swap   ] || echo mkdir -p ~/.nvim-tmp/swap
[ -d ~/.vim-tmp/backup  ] || echo mkdir -p ~/.vim-tmp/backup
[ -d ~/.vim-tmp/swap    ] || echo mkdir -p ~/.vim-tmp/swap

# vim:ft=sh
