import = [
	"~/.local/share/alacritty/themes/themes/solarized_dark.toml"
]

[shell]
program = "/usr/local/bin/fish"
args = ["-l"]

[env]
LC_CTYPE = "en_US.UTF-8"

[window]
#startup_mode = "Maximized"
resize_increments = true
option_as_alt = "Both"
#decorations = "None"
padding = { x = 5, y = 5 }

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 14.0

[colors]
cursor = { text = "#000000", cursor = "#cccccc" }

[cursor]
style = { shape = "Block", blinking = "Off" }

# style = { shape = "Beam", blinking = "Off" }

# style = { shape = "Underline", blinking = "Off" }
# thickness = 0.5



[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  # make Ctrl-/ work to comment lines in Vim
  { key = "Slash", mods = "Control", chars = "\u001f" }
]

[bell]
# animation = "Ease"
# duration = 0
